[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ha-link"
version = "0.1.2"
description = "Manage Home Assistant custom integration symlinks for development"
readme = "README.md"
license = { text = "Apache Software License 2.0" }
authors = [{ name = "g4bri3lDev", email = "admin@g4bri3l.de" }]
requires-python = ">=3.11"
dependencies = [
    "typer",
    "questionary",
    "tomli-w",
    "rich",
]

[project.scripts]
ha-link = "ha_link.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/ha_link"]
